# Kontext-inpaint 伪 mask-free 训练配置

job: train

config:
  name: flux-fill-kontext-inpaint-v1
  training_folder: "/cloud/cloud-ssd1/training_output"

  process:
    - type: finetune
      # 模型路径配置
      vae_path: "/cloud/cloud-ssd1/FLUX.1-Fill-dev/vae"
      model_path: "/cloud/cloud-ssd1/FLUX.1-Fill-dev/transformer"
      text_encoder_path: "/cloud/cloud-ssd1/FLUX.1-Fill-dev/text_encoder"
      text_encoder_2_path: "/cloud/cloud-ssd1/FLUX.1-Fill-dev/text_encoder_2"
      
      # 数据集路径配置
      source_image_dir: "/cloud/cloud-ssd1/new_dataset/source_images"
      target_image_dir: "/cloud/cloud-ssd1/new_dataset/target_images"
      # 注意：不使用mask_dir，因为WhiteMaskDataset会自动生成纯白控制图
      
      # 训练超参数
      resolution: 256  # 降低分辨率要求，适应小尺寸图片
      batch_size: 1
      num_epochs: 1
      lr: 1e-4
      steps: 10000
      
      # 两阶段训练配置
      two_stage_training: true
      stage1_steps: 2000
      stage1_lr: 1e-4
      stage2_lr: 5e-5
      
      device: "cuda"
      
      # 显存优化
      gradient_accumulation_steps: 4